[app]
title = PiuCaniPiuBelli
package.name = piucanipiubelli
package.domain = org.alberto
source.dir = /content
source.main = main.py
requirements = python3,kivy,sqlite3
orientation = portrait
fullscreen = 1

creare un ambiente locale eseguendo i seguenti comandi 
sudo apt update
sudo apt install python3.9 python3.9-venv python3.9-dev git unzip openjdk-17-jdk zip -y
cd /mnt/c/Users/alber/Desktop/GIT/Repository_remote/Piu_cani_piu_belli
python3.9 -m venv kivybuild39
source kivybuild39/bin/activate
pip install --upgrade pip
pip install cython==0.29.36
pip install buildozer
buildozer init
buildozer android clean
buildozer android debug
